import { NextRequest, NextResponse } from "next/server"
import { ZODIAC_SIGNS } from "@/lib/zodiac-data"

const SYSTEM_PROMPT = `Bạn là SoulGem AI - chuyên gia tư vấn vòng tay đá năng lượng cá nhân hóa.

DANH SÁCH ĐÁ CHO PHÉP (dùng CHÍNH XÁC tên này):
1. Thạch anh trắng (#FFFFFF)
2. Thạch anh tím (#9966CC)
3. Mắt hổ (#C29B6F)
4. Thạch anh vàng (#FFD700)
5. Thạch anh hồng (#FFB6C1)
6. Đá mặt trăng (#F0E68C)
7. Aquamarine (#7FFFD4)
8. Fluorite (#8B7DBC)
9. Thạch anh xanh (#00CED1)
10. Obsidian đen (#000000)
11. Đá mặt trời (#FF8C00)

QUY TẮC:
- Chọn 4 loại đá: main (chính) + healing (chữa lành) + boost (tăng cường) + theme (chủ đề)
- Tránh màu người dùng không muốn
- Tính hạt: 6mm (16-20 hạt), 8mm (12-16 hạt)
- Tên vòng phải có ý nghĩa + tên cung hoàng đạo
- Layout: mô tả cách sắp xếp

RESPONSE PHẢI LÀ JSON STRICT (không text khác):
{
  "vongTayDeXuat": {
    "tenVong": "string",
    "vibe": "mạnh mẽ" | "nhẹ nhàng" | "bí ẩn",
    "phongCach": "string",
    "coTayCm": number,
    "nganSach": number,
    "kichThuocHatMm": 6 | 8,
    "soHatDuKien": "string",
    "bangDa": [
      { "vaiTro": "main" | "healing" | "boost" | "theme", "tenDa": "string", "mauSac": "hex", "yNghia": "string" }
    ],
    "charmGoiY": [{ "tenCharm": "string", "yNghia": "string" }],
    "layoutDeXuat": "string",
    "mauChuDao": ["hex1", "hex2"],
    "negativeFiltersApplied": ["string"],
    "lyDoChon": ["string", "string", "string"]
  },
  "readingCard": {
    "tieuDe": "string",
    "thongDiepChinh": "string",
    "giaiThichNgan": ["string", "string"],
    "affirmation": { "text": "string", "autoGenerated": boolean }
  }
}`

interface RecommendationRequest {
  ngaySinh: string
  cumHoangDao: string
  gioiTinh: string
  phanTu: string
  trangThaiTinhThan: string
  raoCan: string
  suMenh: string
  vibeNangLuong: string
  phongCach: string
  mauKhongMuon: string
  coTayCm: number
  nganSach: number
  affirmation: string
}

function buildUserPrompt(data: RecommendationRequest): string {
  const zodiac = ZODIAC_SIGNS.find((z) => z.id === data.cumHoangDao)
  const affirmationStatus = data.affirmation ? "người dùng cung cấp" : "tự động tạo"

  return `Dữ liệu người dùng:
- Cung hoàng đạo: ${zodiac?.name} (Mệnh: ${zodiac?.element}) | Ngày sinh: ${data.ngaySinh}
- Giới tính: ${data.gioiTinh} | Phần tử: ${data.phanTu}
- Trạng thái tinh thần: ${data.trangThaiTinhThan}
- Rào cản: ${data.raoCan} | Sứ mệnh: ${data.suMenh}
- Vibe: ${data.vibeNangLuong} | Phong cách: ${data.phongCach}
- Màu KHÔNG muốn: ${data.mauKhongMuon}
- Cổ tay: ${data.coTayCm}cm | Ngân sách: ${data.nganSach}đ
- Affirmation (${affirmationStatus}): "${data.affirmation}"

Tạo đầy đủ bộ đá + reading card (JSON strict).`
}

export async function POST(request: NextRequest) {
  try {
    const data: RecommendationRequest = await request.json()

    // Validate
    const required = [
      "ngaySinh",
      "cumHoangDao",
      "gioiTinh",
      "phanTu",
      "trangThaiTinhThan",
      "raoCan",
      "suMenh",
      "vibeNangLuong",
      "phongCach",
      "mauKhongMuon",
    ]
    const missing = required.filter((field) => !data[field as keyof RecommendationRequest])

    if (missing.length > 0) {
      return NextResponse.json({ error: `Missing fields: ${missing.join(", ")}` }, { status: 400 })
    }

    const apiKey = process.env.OPENAI_API_KEY
    if (!apiKey) {
      console.error("[v0] OPENAI_API_KEY not found")
      return NextResponse.json({ error: "API key not configured" }, { status: 500 })
    }

    console.log("[v0] Calling OpenAI with user data")

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: buildUserPrompt(data) },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      }),
    })

    if (!response.ok) {
      const error = await response.json()
      console.error("[v0] OpenAI error:", error)
      return NextResponse.json(
        { error: `OpenAI error: ${error.error?.message || "Unknown"}` },
        { status: response.status }
      )
    }

    const result = await response.json()
    const content = result.choices[0]?.message?.content

    if (!content) {
      console.error("[v0] No content from OpenAI")
      return NextResponse.json({ error: "No content in response" }, { status: 500 })
    }

    console.log("[v0] OpenAI response length:", content.length)

    // Extract JSON
    let jsonStr = content.trim()
    if (jsonStr.startsWith("```json")) jsonStr = jsonStr.slice(7)
    if (jsonStr.startsWith("```")) jsonStr = jsonStr.slice(3)
    if (jsonStr.endsWith("```")) jsonStr = jsonStr.slice(0, -3)
    jsonStr = jsonStr.trim()

    let parsed
    try {
      parsed = JSON.parse(jsonStr)
    } catch (err) {
      console.error("[v0] JSON parse failed:", err)
      return NextResponse.json({ error: "Invalid JSON from AI" }, { status: 500 })
    }

    if (!parsed.vongTayDeXuat || !parsed.readingCard) {
      console.error("[v0] Invalid structure:", parsed)
      return NextResponse.json({ error: "Invalid response structure" }, { status: 500 })
    }

    console.log("[v0] Recommendation generated successfully")
    return NextResponse.json(parsed)
  } catch (error) {
    console.error("[v0] API error:", error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    )
  }
}

export async function GET() {
  return NextResponse.json({
    message: "SoulGem AI Recommendation API",
    endpoint: "POST /api/recommend-bracelet",
    description: "Generate personalized bracelet recommendation",
  })
}
