// Optimized Energy Analysis & Bracelet Recommendation Engine
// lib/analyzeEnergy.ts

import { getZodiacByDate, getElementDisplay, ALLOWED_STONES, getRandomAffirmation } from "./zodiac-data"

// Types
interface UserAnswers {
  birthDate: string // YYYY-MM-DD
  cumHoangDao?: string // zodiac
  gioiTinh: string // gender: nữ/nam/khác
  phanTu?: string // element from form
  trangThaiTinhThan: string[] // emotionalState array
  raoCan?: string // barrier
  suMenh: string[] // lifeGoal array
  vibeNangLuong: string // energyVibe
  phongCach: string // fashionStyle
  mauKhongMuon?: string // forbidden colors (comma-separated)
  coTayCm: number // wristSize
  nganSach: number // budget
  affirmation?: string // custom affirmation
}

interface Stone {
  id: string
  name: string
  color: string
  vibes: string[]
  meaning: string
}

interface SelectedStone {
  vaiTro: "main" | "healing" | "boost" | "theme"
  tenDa: string
  mauSac: string
  yNghia: string
  lyDo: string
}

interface VongTayDeXuat {
  tenVong: string
  vibe: string
  phongCach: string
  coTayCm: number
  nganSach: number
  kichThuocHatMm: number
  soHatDuKien: string
  bangDa: SelectedStone[]
  mauChuDao: string[]
  lyDoChon: string[]
}

interface ReadingCard {
  tieuDe: string
  thongDiepChinh: string
  giaiThichNgan: string[]
  affirmation: {
    text: string
    autoGenerated: boolean
  }
  energyDescription: string
}

// Color filtering map (Vietnamese color names)
const COLOR_FILTER_MAP: Record<string, string[]> = {
  "vàng": ["citrine"],
  "cam": ["sunstone"],
  "đỏ": ["garnet"],
  "nóng": ["citrine", "sunstone", "garnet"],
  "tím": ["amethyst"],
  "xanh": ["fluorite", "peridot", "aquamarine", "labradorite"],
  "xanh dương": ["aquamarine"],
  "xanh lá": ["peridot"],
  "hồng": ["rose-quartz"],
  "đa sắc": ["labradorite"],
  "trắng": [],
  "đen": [],
  "lạnh": ["rose-quartz", "moonstone", "aquamarine", "amethyst"],
  "nữ tính": ["rose-quartz", "moonstone"],
}

// Emotional state mapping (tâm trạng → đá ưu tiên)
const EMOTIONAL_STATE_MAP: Record<string, {
  healing: string[]
  main: string
  boost: string
  theme?: string
  reasons: string[]
  affirmationKey: string
}> = {
  // 1. STRESS (Căng thẳng, kiệt sức)
  "stress": {
    healing: ["amethyst", "aquamarine"],
    main: "clear-quartz",
    boost: "fluorite",
    theme: "moonstone",
    reasons: [
      "Amethyst giảm stress và tĩnh lặng tâm trí (mệnh Thủy)",
      "Aquamarine mang lại bình tĩnh sâu sắc (mệnh Thủy)",
      "Clear Quartz khuếch đại năng lượng chữa lành",
      "Fluorite giúp tập trung và loại bỏ tiêu cực",
      "Moonstone cân bằng cảm xúc nữ tính",
    ],
    affirmationKey: "can-thang",
  },
  "can-thang": {
    healing: ["amethyst", "aquamarine"],
    main: "clear-quartz",
    boost: "fluorite",
    theme: "moonstone",
    reasons: [
      "Amethyst giảm căng thẳng và mang lại yên bình",
      "Aquamarine thanh lọc và bình tĩnh (Thủy)",
      "Clear Quartz khuếch đại năng lượng bình yên",
      "Tránh đá nóng (Hỏa) vì bạn cần yên tĩnh",
    ],
    affirmationKey: "can-thang",
  },

  // 2. LOST/CONFUSED (Mông lung, định hướng)
  "lost": {
    healing: ["labradorite", "fluorite"],
    main: "clear-quartz",
    boost: "peridot",
    theme: "labradorite",
    reasons: [
      "Labradorite thức tỉnh tiềm năng ẩn (Khí/Thủy)",
      "Fluorite tăng tập trung và sáng suốt",
      "Clear Quartz khuếch đại sự rõ ràng",
      "Peridot tái sinh hướng đi và buông bỏ bế tắc",
    ],
    affirmationKey: "mong-lung",
  },
  "mong-lung": {
    healing: ["labradorite", "fluorite"],
    main: "clear-quartz",
    boost: "peridot",
    theme: "labradorite",
    reasons: [
      "Labradorite giúp tìm thấy phương hướng mới",
      "Fluorite làm sáng suốt quyết định",
      "Peridot hỗ trợ tái sinh năng lượng",
    ],
    affirmationKey: "mong-lung",
  },

  // 3. ANXIOUS/RESTLESS (Bất an, khó ngủ)
  "anxious": {
    healing: ["amethyst", "moonstone"],
    main: "rose-quartz",
    boost: "aquamarine",
    theme: "moonstone",
    reasons: [
      "Amethyst giảm lo lắng và giúp ngủ ngon (Thủy)",
      "Moonstone cân bằng cảm xúc nữ tính (Nước)",
      "Rose Quartz tự yêu bản thân, an toàn tim",
      "Aquamarine thanh lọc sợ hãi",
    ],
    affirmationKey: "bat-an",
  },
  "bat-an": {
    healing: ["amethyst", "moonstone"],
    main: "rose-quartz",
    boost: "aquamarine",
    theme: "moonstone",
    reasons: [
      "Amethyst là viên đá tuyệt vời để giảm bất an",
      "Rose Quartz mở tim và tạo cảm giác an toàn",
      "Moonstone hỗ trợ ngủ ngon",
    ],
    affirmationKey: "bat-an",
  },

  // 4. ANGRY/IRRITABLE (Nóng nảy, dễ cáu gắt)
  "angry": {
    healing: ["aquamarine", "rose-quartz"],
    main: "clear-quartz",
    boost: "amethyst",
    theme: "aquamarine",
    reasons: [
      "Aquamarine làm mát năng lượng Hỏa (Thủy)",
      "Rose Quartz chữa lành tim, giảm giận dữ",
      "Amethyst tĩnh lặng cảm xúc bốc đỏ",
      "TRÁNH: Đá nóng (Citrine, Sunstone, Garnet)",
    ],
    affirmationKey: "nong-nay",
  },
  "nong-nay": {
    healing: ["aquamarine", "rose-quartz"],
    main: "clear-quartz",
    boost: "amethyst",
    theme: "aquamarine",
    reasons: [
      "Aquamarine hạ hỏa, mang lại bình tĩnh (Thủy)",
      "Rose Quartz chữa lành và mềm mỏng cảm xúc",
      "Tránh đá nóng hoàn toàn",
    ],
    affirmationKey: "nong-nay",
  },

  // 5. BORED/UNMOTIVATED (Tẻ nhạt, thiếu động lực)
  "bored": {
    healing: ["clear-quartz"],
    main: "citrine",
    boost: "sunstone",
    theme: "sunstone",
    reasons: [
      "Citrine kích thích năng lượng dương (Hỏa)",
      "Sunstone mang lại vui vẻ và sinh lực",
      "Garnet nếu muốn đam mê mạnh mẽ",
      "Khuếch đại tích cực để khơi dậy động lực",
    ],
    affirmationKey: "te-nhat",
  },
  "te-nhat": {
    healing: ["clear-quartz"],
    main: "citrine",
    boost: "sunstone",
    theme: "garnet",
    reasons: [
      "Citrine tăng năng lượng tích cực (Hỏa)",
      "Sunstone mang lại niềm vui",
      "Garnet đốt lửa đam mê nếu muốn mạnh mẽ",
    ],
    affirmationKey: "te-nhat",
  },

  // 6. HAPPY/PEACEFUL (Vui vẻ, bình yên)
  "happy": {
    healing: ["rose-quartz", "moonstone"],
    main: "citrine",
    boost: "sunstone",
    theme: "rose-quartz",
    reasons: [
      "Citrine duy trì năng lượng dương tích cực",
      "Sunstone khuếch đại vui vẻ và sinh lực",
      "Rose Quartz/Moonstone nuôi dưỡng hạnh phúc",
      "Khuếch đại trạng thái tốt hiện tại",
    ],
    affirmationKey: "vui-ve",
  },
  "vui-ve": {
    healing: ["rose-quartz", "moonstone"],
    main: "citrine",
    boost: "sunstone",
    theme: "rose-quartz",
    reasons: [
      "Citrine/Sunstone giữ năng lượng dương",
      "Rose Quartz/Moonstone nuôi dưỡng hạnh phúc",
      "Duy trì trạng thái tốt đẹp",
    ],
    affirmationKey: "vui-ve",
  },

  // DEFAULT
  "default": {
    healing: ["amethyst"],
    main: "clear-quartz",
    boost: "rose-quartz",
    theme: "moonstone",
    reasons: ["Cân bằng ngũ hành, hỗ trợ toàn diện"],
    affirmationKey: "default",
  },
}

/**
 * Filter stones by forbidden colors (mauKhongMuon)
 */
function filterStonesByColor(forbiddenColors?: string): Stone[] {
  if (!forbiddenColors || forbiddenColors.trim() === "") {
    return ALLOWED_STONES
  }

  const forbidden = forbiddenColors
    .toLowerCase()
    .split(",")
    .map((c) => c.trim())
    .filter((c) => c.length > 0)

  const forbiddenStoneIds = new Set<string>()

  forbidden.forEach((color) => {
    const stonesToAvoid = COLOR_FILTER_MAP[color] || []
    stonesToAvoid.forEach((id) => forbiddenStoneIds.add(id))
  })

  return ALLOWED_STONES.filter((stone) => !forbiddenStoneIds.has(stone.id))
}

/**
 * Get emotional state key from user answers
 */
function getEmotionalStateKey(emotionalStates?: string[]): string {
  if (!emotionalStates || emotionalStates.length === 0) return "default"

  const state = emotionalStates[0].toLowerCase()

  // Match Vietnamese names
  if (state.includes("căng") || state.includes("stress")) return "can-thang"
  if (state.includes("mông") || state.includes("định") || state.includes("lost")) return "mong-lung"
  if (state.includes("bất") || state.includes("lo") || state.includes("anxious")) return "bat-an"
  if (state.includes("nóng") || state.includes("giận") || state.includes("angry")) return "nong-nay"
  if (state.includes("tẻ") || state.includes("bored")) return "te-nhat"
  if (state.includes("vui") || state.includes("happy")) return "vui-ve"

  return "default"
}

/**
 * Check if stones have conflicting energy (hot vs cold)
 */
function hasEnergyConflict(stoneIds: string[]): boolean {
  const hot = ["citrine", "sunstone", "garnet"]
  const cold = ["rose-quartz", "moonstone", "aquamarine", "amethyst"]

  const hasHot = stoneIds.some((id) => hot.includes(id))
  const hasCold = stoneIds.some((id) => cold.includes(id))

  // Allow mix only if it's balanced (e.g., 1 hot + 1 cold for balance)
  // Avoid: all hot + all cold imbalanced mix
  return hasHot && hasCold && stoneIds.length <= 3
}

/**
 * Main analysis function
 */
export function analyzeEnergy(user: UserAnswers) {
  // Parse date
  const [year, month, day] = user.birthDate.split("-").map(Number)
  const zodiac = getZodiacByDate(day, month)
  const elementDisplay = getElementDisplay(zodiac.element)

  // Filter available stones
  const availableStones = filterStonesByColor(user.mauKhongMuon)

  // Get emotional state mapping
  const stateKey = getEmotionalStateKey(user.trangThaiTinhThan)
  const stateMapping = EMOTIONAL_STATE_MAP[stateKey] || EMOTIONAL_STATE_MAP["default"]

  // Select stones
  const selectedStones: SelectedStone[] = []

  // Main stone
  let mainStone = availableStones.find((s) => s.id === stateMapping.main)

  // Adjust main by lifeGoal
  if (user.suMenh && user.suMenh.length > 0) {
    const goal = user.suMenh[0].toLowerCase()
    if (goal.includes("tài") || goal.includes("wealth")) {
      mainStone = availableStones.find((s) => s.id === "citrine") || mainStone
    } else if (goal.includes("tình") || goal.includes("love")) {
      mainStone = availableStones.find((s) => s.id === "rose-quartz") || mainStone
    } else if (goal.includes("sức") || goal.includes("health")) {
      mainStone = availableStones.find((s) => s.id === "clear-quartz") || mainStone
    } else if (goal.includes("khôn") || goal.includes("wisdom")) {
      mainStone = availableStones.find((s) => s.id === "amethyst") || mainStone
    }
  }

  if (mainStone) {
    selectedStones.push({
      vaiTro: "main",
      tenDa: mainStone.name,
      mauSac: mainStone.color,
      yNghia: mainStone.meaning,
      lyDo: stateMapping.reasons[0] || `Đá chính cho mục tiêu của bạn`,
    })
  }

  // Healing stones
  const healingStoneIds = stateMapping.healing.filter((id) => availableStones.find((s) => s.id === id))

  // Adjust healing by gender
  if (user.gioiTinh?.toLowerCase().includes("nữ")) {
    if (!healingStoneIds.includes("moonstone")) healingStoneIds.push("moonstone")
  }

  healingStoneIds.forEach((id, idx) => {
    if (idx < 2) {
      // Max 2 healing stones
      const stone = availableStones.find((s) => s.id === id)
      if (stone && stone.id !== mainStone?.id) {
        selectedStones.push({
          vaiTro: "healing",
          tenDa: stone.name,
          mauSac: stone.color,
          yNghia: stone.meaning,
          lyDo: stateMapping.reasons[idx + 1] || `Đá chữa lành cho tâm trạng của bạn`,
        })
      }
    }
  })

  // Boost stone
  const boostStone = availableStones.find((s) => s.id === stateMapping.boost)
  if (boostStone && boostStone.id !== mainStone?.id && !selectedStones.some((s) => s.tenDa === boostStone.name)) {
    selectedStones.push({
      vaiTro: "boost",
      tenDa: boostStone.name,
      mauSac: boostStone.color,
      yNghia: boostStone.meaning,
      lyDo: `Tăng cường năng lượng ${user.vibeNangLuong}`,
    })
  }

  // Theme stone (based on fashion style)
  let themeStone: Stone | undefined
  if (user.phongCach) {
    const style = user.phongCach.toLowerCase()
    if (style.includes("thanh") || style.includes("elegant")) {
      themeStone = availableStones.find((s) => s.id === "labradorite") || availableStones.find((s) => s.id === stateMapping.theme)
    } else if (style.includes("sôi") || style.includes("vibrant")) {
      themeStone = availableStones.find((s) => s.id === "sunstone")
    } else if (style.includes("tối") || style.includes("minimalist")) {
      themeStone = availableStones.find((s) => s.id === "clear-quartz")
    } else if (style.includes("tình") || style.includes("romantic")) {
      themeStone = availableStones.find((s) => s.id === "rose-quartz")
    } else if (stateMapping.theme) {
      themeStone = availableStones.find((s) => s.id === stateMapping.theme)
    }
  }

  if (themeStone && !selectedStones.some((s) => s.tenDa === themeStone?.name)) {
    selectedStones.push({
      vaiTro: "theme",
      tenDa: themeStone.name,
      mauSac: themeStone.color,
      yNghia: themeStone.meaning,
      lyDo: `Đá chủ đề theo phong cách ${user.phongCach}`,
    })
  }

  // Check for conflicts and adjust
  const selectedIds = selectedStones.map((s) => {
    const stone = ALLOWED_STONES.find((st) => st.name === s.tenDa)
    return stone?.id || ""
  })

  if (hasEnergyConflict(selectedIds) && selectedIds.length > 4) {
    // Remove least important stone if too many conflicting energies
    selectedStones.pop()
  }

  // Calculate bracelet specs
  const estimatedBeads = Math.ceil((user.coTayCm * 10) / 8)
  const mainBeadCount = Math.max(3, Math.ceil(estimatedBeads / selectedStones.length))

  // Build result
  const mauChuDao = [...new Set(selectedStones.map((s) => s.mauSac))]

  const vongTayDeXuat: VongTayDeXuat = {
    tenVong: `Vòng Tay ${zodiac.name} - ${user.phongCach}`,
    vibe: user.vibeNangLuong,
    phongCach: user.phongCach,
    coTayCm: user.coTayCm,
    nganSach: user.nganSach,
    kichThuocHatMm: 8,
    soHatDuKien: `${estimatedBeads} hạt`,
    bangDa: selectedStones,
    mauChuDao: mauChuDao,
    lyDoChon: selectedStones.map((s) => s.lyDo),
  }

  // Affirmation
  const affirmationText =
    user.affirmation ||
    getRandomAffirmation(user.trangThaiTinhThan?.[0] || stateMapping.affirmationKey)

  // Energy description
  const energyDescription = buildEnergyDescription(
    zodiac.element,
    stateKey,
    selectedStones,
    elementDisplay
  )

  const readingCard: ReadingCard = {
    tieuDe: `Lời nhắn từ ${zodiac.name}`,
    thongDiepChinh: `Hành trình của bạn gắn liền với sự ${user.vibeNangLuong}`,
    giaiThichNgan: [
      `Cung ${zodiac.name} (mệnh ${zodiac.element}) mang đặc điểm của sức sáng tạo và biến đổi.`,
      elementDisplay,
      `Những viên đá trong vòng tay này sẽ giúp bạn khai thác tối đa tiềm năng và bảo vệ năng lượng của mình.`,
    ],
    affirmation: {
      text: affirmationText,
      autoGenerated: !user.affirmation,
    },
    energyDescription: energyDescription,
  }

  return {
    vongTayDeXuat,
    readingCard,
    zodiacInfo: {
      name: zodiac.name,
      element: elementDisplay,
      birthstone: zodiac.birthstone,
    },
  }
}

/**
 * Build energy description based on state and selected stones
 */
function buildEnergyDescription(
  element: string,
  stateKey: string,
  selectedStones: SelectedStone[],
  elementDisplay: string
): string {
  const stoneNames = selectedStones.slice(0, 3).map((s) => s.tenDa).join(", ")

  const descriptions: Record<string, string> = {
    "can-thang": `Năng lượng của bạn đang cần thanh lọc và nghỉ ngơi sâu. ${stoneNames} sẽ mang lại sự tĩnh lặng và cân bằng cảm xúc. ${elementDisplay}`,
    "mong-lung": `Năng lượng của bạn đang trong giai đoạn chuyển tiếp. ${stoneNames} giúp thức tỉnh trực giác và mang lại sự rõ ràng để tìm thấy phương hướng mới. ${elementDisplay}`,
    "bat-an": `Năng lượng của bạn cần được nuôi dưỡng để tìm lại sự an toàn nội tâm. ${stoneNames} sẽ giúp bạn cảm thấy bảo vệ và yên bình. ${elementDisplay}`,
    "nong-nay": `Năng lượng của bạn đang nóng, cần bổ sung Thủy để làm mát và cân bằng. ${stoneNames} sẽ giúp bạn lựa chọn bình tĩnh và kiểm soát cảm xúc. ${elementDisplay}`,
    "te-nhat": `Năng lượng của bạn cần được khơi dậy để tìm lại niềm vui. ${stoneNames} sẽ tăng cường sức sống, tích cực và động lực. ${elementDisplay}`,
    "vui-ve": `Năng lượng của bạn đang rất tích cực. ${stoneNames} giúp duy trì và lan tỏa hạnh phúc xung quanh. ${elementDisplay}`,
    "default": `Năng lượng của bạn cần cân bằng toàn diện. ${stoneNames} sẽ hỗ trợ bạn trên hành trình phát triển. ${elementDisplay}`,
  }

  return descriptions[stateKey] || descriptions["default"]
}

/**
 * Export example usage
 */
export const EXAMPLE_USAGE = `
// Example: User with stress, forbidden warm colors, female, love goal
const userAnswers: UserAnswers = {
  birthDate: "1998-05-15",
  cumHoangDao: "kim-nguu",
  gioiTinh: "nữ",
  phanTu: "thổ",
  trangThaiTinhThan: ["Căng thẳng", "Kiệt sức"],
  raoCan: "overthinking",
  suMenh: ["bình yên", "tình yêu"],
  vibeNangLuong: "nhẹ nhàng",
  phongCach: "thanh lịch",
  mauKhongMuon: "vàng, cam, nóng",
  coTayCm: 16.5,
  nganSach: 800000,
  affirmation: undefined,
}

const result = analyzeEnergy(userAnswers)
// Output:
// - Main stone: Clear Quartz (trung tính)
// - Healing: Amethyst + Aquamarine (tránh vàng/nóng)
// - Boost: Fluorite
// - Theme: Moonstone (nữ tính)
// - Gam màu: Tím, xanh dương, trắng, trắng ánh xanh
// - Affirmation: "Tôi buông bỏ căng thẳng và đón nhận bình yên."
`
