// SoulGem AI - Bracelet Recommendation Engine
// Rule-based with AI enhancement for personalized energy reading

export interface BraceletRecommendationInput {
  ngaySinh?: string
  cungHoangDao?: string
  gioiTinh?: string
  yeuToThienNhien?: string
  trangThaiTinhThan?: string
  raoCan?: string
  suMenh?: string
  vibe?: string
  phongCach?: string
  mauKhongMuon?: string
  coTayCm?: number
  nganSach?: number
  affirmation?: string
}

export interface DaInfo {
  vaiTro: "main" | "healing" | "boost" | "theme"
  tenDa: string
  mauSac: string
  yNghia: string
}

export interface BraceletRecommendation {
  project: {
    name: string
    concept: string
    businessModel: string
  }
  input: BraceletRecommendationInput
  result: {
    tomTatChanDung: string[]
    vongTayDeXuat: {
      tenVong: string
      vibe: string
      phongCach: string
      coTayCm: number
      nganSach: number
      kichThuocHatMm: number
      soHatDuKien: string
      bangDa: DaInfo[]
      charmGoiY: Array<{ tenCharm: string; yNghia: string }>
      layoutDeXuat: string
      mauChuDao: string[]
      negativeFiltersApplied: string[]
      lyDoChon: string[]
    }
    readingCard: {
      tieuDe: string
      thongDiepChinh: string
      giaiThichNgan: string[]
      affirmation: {
        text: string
        autoGenerated: boolean
      }
    }
  }
}

// Danh sách đá được phép dùng (Chỉ 11 loại đá)
const ALLOWED_STONES = [
  "Thạch Anh Vàng (Citrine)",
  "Thạch Anh Trắng (Clear Quartz)",
  "Thạch Anh Tím (Amethyst)",
  "Fluorite",
  "Đá Mặt Trăng (Moonstone)",
  "Đá Mặt Trời (Sunstone)",
  "Đá Labradorite (Đá Hắc Nguyệt Quang)",
  "Peridot",
  "Aquamarine",
  "Thạch Anh Hồng (Rose Quartz)",
  "Ngọc Hồng Lựu (Garnet)",
]

// Color mapping (ánh xạ sang 11 đá)
const STONE_COLORS: Record<string, string> = {
  "Thạch Anh Vàng (Citrine)": "#FFD700",
  "Thạch Anh Trắng (Clear Quartz)": "#FFFFFF",
  "Thạch Anh Tím (Amethyst)": "#9966CC",
  "Fluorite": "#8B7DBC",
  "Đá Mặt Trăng (Moonstone)": "#F0E68C",
  "Đá Mặt Trời (Sunstone)": "#FF8C00",
  "Đá Labradorite (Đá Hắc Nguyệt Quang)": "#A8DADC",
  "Peridot": "#9ACD32",
  "Aquamarine": "#7FFFD4",
  "Thạch Anh Hồng (Rose Quartz)": "#FFB6C1",
  "Ngọc Hồng Lựu (Garnet)": "#C71585",
}

// Stone meaning mapping (từ zodiac-data.ts)
const STONE_MEANINGS: Record<string, string> = {
  "Thạch Anh Vàng (Citrine)":
    "Thu hút tài lộc, năng lượng tích cực, thành công, tự tin",
  "Thạch Anh Trắng (Clear Quartz)":
    "Khuếch đại năng lượng, thanh tịnh, làm rõ ý định, cân bằng tổng thể",
  "Thạch Anh Tím (Amethyst)":
    "Giảm stress, tăng trực giác, bảo vệ tâm trí, mang lại bình yên sâu lắng",
  "Fluorite":
    "Tăng tập trung, bảo vệ cảm xúc, giúp suy nghĩ rõ ràng, loại bỏ năng lượng tiêu cực",
  "Đá Mặt Trăng (Moonstone)":
    "Cân bằng cảm xúc, tăng trực giác, nuôi dưỡng nữ tính, hỗ trợ giấc ngủ sâu",
  "Đá Mặt Trời (Sunstone)":
    "Tăng sinh lực, vui vẻ, tự tin, kết nối với năng lượng mặt trời tích cực",
  "Đá Labradorite (Đá Hắc Nguyệt Quang)":
    "Thức tỉnh tiềm năng, bảo vệ aura, hỗ trợ thay đổi tích cực, tăng sáng tạo",
  "Peridot":
    "Chữa lành tim, thu hút thịnh vượng, buông bỏ gánh nặng, tái sinh năng lượng",
  "Aquamarine":
    "Mang lại bình tĩnh, hỗ trợ giao tiếp chân thành, thanh lọc cảm xúc",
  "Thạch Anh Hồng (Rose Quartz)":
    "Tự yêu bản thân, mở lòng đón tình yêu, chữa lành vết thương tình cảm",
  "Ngọc Hồng Lựu (Garnet)":
    "Tăng sức sống, đam mê, grounding năng lượng, bảo vệ và kích hoạt ý chí",
}

// Rule-based mapping functions (cập nhật cho 11 đá)
function getHealingStone(trangThaiTinhThan?: string): string {
  if (!trangThaiTinhThan) return "Thạch Anh Tím (Amethyst)" // default

  const mappings: Record<string, string> = {
    "stress": "Thạch Anh Tím (Amethyst)",
    "căng thẳng": "Thạch Anh Tím (Amethyst)",
    "lost": "Đá Labradorite (Đá Hắc Nguyệt Quang)",
    "mông lung": "Đá Labradorite (Đá Hắc Nguyệt Quang)",
    "anxious": "Đá Mặt Trăng (Moonstone)",
    "bất an": "Đá Mặt Trăng (Moonstone)",
    "angry": "Aquamarine",
    "nóng nảy": "Aquamarine",
    "bored": "Thạch Anh Vàng (Citrine)",
    "tẻ nhạt": "Thạch Anh Vàng (Citrine)",
    "happy": "Thạch Anh Hồng (Rose Quartz)",
    "vui vẻ": "Thạch Anh Hồng (Rose Quartz)",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (trangThaiTinhThan.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch Anh Tím (Amethyst)"
}

function getBoostStone(raoCan?: string): string {
  if (!raoCan) return "Fluorite" // default - tập trung

  const mappings: Record<string, string> = {
    "procrastination": "Fluorite",
    "trì hoãn": "Fluorite",
    "confidence": "Đá Mặt Trời (Sunstone)",
    "tự tin": "Đá Mặt Trời (Sunstone)",
    "unclear": "Thạch Anh Trắng (Clear Quartz)",
    "mông lung": "Thạch Anh Trắng (Clear Quartz)",
    "health": "Peridot",
    "sức khỏe": "Peridot",
    "energy": "Ngọc Hồng Lựu (Garnet)",
    "năng lượng": "Ngọc Hồng Lựu (Garnet)",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (raoCan.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Fluorite"
}

function getThemeStone(suMenh?: string): string {
  if (!suMenh) return "Thạch Anh Vàng (Citrine)" // default

  const mappings: Record<string, string> = {
    "wealth": "Thạch Anh Vàng (Citrine)",
    "tài lộc": "Thạch Anh Vàng (Citrine)",
    "love": "Thạch Anh Hồng (Rose Quartz)",
    "tình yêu": "Thạch Anh Hồng (Rose Quartz)",
    "wisdom": "Fluorite",
    "khôn ngoan": "Fluorite",
    "health": "Thạch Anh Tím (Amethyst)",
    "sức khỏe": "Thạch Anh Tím (Amethyst)",
    "peace": "Thạch Anh Trắng (Clear Quartz)",
    "bình yên": "Thạch Anh Trắng (Clear Quartz)",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (suMenh.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch Anh Vàng (Citrine)"
}

function getMainStone(yeuToThienNhien?: string): string {
  if (!yeuToThienNhien) return "Thạch Anh Trắng (Clear Quartz)"

  const mappings: Record<string, string> = {
    "fire": "Thạch Anh Vàng (Citrine)",
    "hỏa": "Thạch Anh Vàng (Citrine)",
    "water": "Aquamarine",
    "nước": "Aquamarine",
    "earth": "Fluorite",
    "thổ": "Fluorite",
    "air": "Thạch Anh Trắng (Clear Quartz)",
    "khí": "Thạch Anh Trắng (Clear Quartz)",
    "wood": "Peridot",
    "mộc": "Peridot",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (yeuToThienNhien.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch Anh Trắng (Clear Quartz)"
}

function getCharmSuggestions(
  suMenh?: string
): Array<{ tenCharm: string; yNghia: string }> {
  if (!suMenh) {
    return [
      { tenCharm: "Hoa Sen", yNghia: "Bình an, tinh khiết" },
      { tenCharm: "Chữ Lộc", yNghia: "Tài lộc, may mắn" },
    ]
  }

  const mappings: Record<
    string,
    Array<{ tenCharm: string; yNghia: string }>
  > = {
    wealth: [
      { tenCharm: "Tiền Tài", yNghia: "Hấp dẫn tài lộc, may mắn kinh doanh" },
      {
        tenCharm: "Sự Nghiệp",
        yNghia: "Thăng tiến, phát triển công việc",
      },
    ],
    love: [
      { tenCharm: "Trái Tim", yNghia: "Tình yêu, kết nối" },
      { tenCharm: "Đôi Cánh", yNghia: "Tự do, kết nối linh hồn" },
    ],
    wisdom: [
      { tenCharm: "Sách", yNghia: "Học tập, trí tuệ" },
      { tenCharm: "Mắt Thứ Ba", yNghia: "Trực giác, ý thức" },
    ],
    health: [
      { tenCharm: "Hoa Sen", yNghia: "Sạch sẽ, bình yên" },
      {
        tenCharm: "Cây Sống",
        yNghia: "Sức sống, phục hồi",
      },
    ],
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (suMenh?.toLowerCase().includes(key)) {
      return value
    }
  }

  return [
    { tenCharm: "Bình Yên", yNghia: "Cân bằng năng lượng" },
  ]
}

function calculateBeadCount(coTayCm: number = 16): string {
  if (coTayCm <= 15) return "17-19"
  if (coTayCm <= 17) return "19-21"
  if (coTayCm <= 19) return "21-23"
  return "23-25"
}

function getBeadSize(nganSach: number = 99000): number {
  return nganSach >= 149000 ? 8 : 6
}

function getLayoutSuggestion(phongCach?: string, vibe?: string): string {
  if (phongCach?.toLowerCase().includes("minimal")) {
    return "1-2 loại đá chính, bố cục sạch sẽ, 1 charm nhỏ tinh tế"
  }
  if (phongCach?.toLowerCase().includes("nổi loạn")) {
    return "Tương phản mạnh, hạt nổi bật, layout phá cách và cá tính"
  }
  if (phongCach?.toLowerCase().includes("vintage")) {
    return "Tone đất ấm, đá mờ, charm cổ điển, bố cục truyền thống"
  }
  if (phongCach?.toLowerCase().includes("nữ tính")) {
    return "Tông hồng/tím, charm tim/hoa, layout mềm mại và nữ tính"
  }

  // Default based on vibe
  if (vibe?.toLowerCase().includes("mạnh")) {
    return "Tương phản rõ, điểm nhấn mạnh, layout cân đối nhưng nổi bật"
  }

  return "Bố cục cân đối, dễ phối đồ, màu sắc hài hòa, charm đa dụng"
}

function getMainColors(
  healingStone: string,
  boostStone: string,
  vibe?: string
): string[] {
  const stoneColorMap: Record<string, string> = STONE_COLORS

  const primary = stoneColorMap[healingStone] || "#9966CC"
  const secondary = stoneColorMap[boostStone] || "#B8860B"

  if (vibe?.toLowerCase().includes("nhẹ")) {
    return [primary, secondary]
  }

  return [secondary, primary]
}

function applyNegativeFilters(
  bangDa: DaInfo[],
  mauKhongMuon?: string
): { bangDa: DaInfo[]; applied: string[] } {
  const applied: string[] = []

  if (!mauKhongMuon || mauKhongMuon.toLowerCase().includes("không")) {
    return { bangDa, applied }
  }

  // Remove dark stones if dark tone not wanted
  if (
    mauKhongMuon.toLowerCase().includes("tối") ||
    mauKhongMuon.toLowerCase().includes("đen")
  ) {
    bangDa = bangDa.filter((d) => !["Ngọc Hồng Lựu (Garnet)"].includes(d.tenDa))
    if (!bangDa.find((d) => d.vaiTro === "boost")) {
      bangDa.push({
        vaiTro: "boost",
        tenDa: "Thạch Anh Trắng (Clear Quartz)",
        mauSac: STONE_COLORS["Thạch Anh Trắng (Clear Quartz)"],
        yNghia: STONE_MEANINGS["Thạch Anh Trắng (Clear Quartz)"],
      })
    }
    applied.push("Loại bỏ đá tông tối (Garnet)")
  }

  // Limit colors if too many wanted
  if (
    mauKhongMuon.toLowerCase().includes("nhiều") ||
    mauKhongMuon.toLowerCase().includes("sặc")
  ) {
    if (bangDa.length > 3) {
      bangDa = bangDa.slice(0, 2)
      bangDa.push({
        vaiTro: "theme",
        tenDa: "Thạch Anh Trắng (Clear Quartz)",
        mauSac: STONE_COLORS["Thạch Anh Trắng (Clear Quartz)"],
        yNghia: STONE_MEANINGS["Thạch Anh Trắng (Clear Quartz)"],
      })
    }
    applied.push("Giới hạn số loại đá (tối giản màu sắc)")
  }

  return { bangDa, applied }
}

export function getBraceletRecommendation(
  input: BraceletRecommendationInput
): BraceletRecommendation {
  // Apply fallbacks for missing data
  const coTayCm = input.coTayCm || 16
  const nganSach = input.nganSach || 99000
  const kichThuocHatMm = getBeadSize(nganSach)
  const soHatDuKien = calculateBeadCount(coTayCm)

  // Get stone recommendations
  const mainStone = getMainStone(input.yeuToThienNhien)
  const healingStone = getHealingStone(input.trangThaiTinhThan)
  const boostStone = getBoostStone(input.raoCan)
  const themeStone = getThemeStone(input.suMenh)

  // Build bộ đá
  let bangDa: DaInfo[] = [
    {
      vaiTro: "main",
      tenDa: mainStone,
      mauSac: STONE_COLORS[mainStone] || "#F5F5F5",
      yNghia: STONE_MEANINGS[mainStone] || "Năng lượng chính",
    },
    {
      vaiTro: "healing",
      tenDa: healingStone,
      mauSac: STONE_COLORS[healingStone] || "#9966CC",
      yNghia: STONE_MEANINGS[healingStone] || "Chữa lành",
    },
    {
      vaiTro: "boost",
      tenDa: boostStone,
      mauSac: STONE_COLORS[boostStone] || "#B8860B",
      yNghia: STONE_MEANINGS[boostStone] || "Tăng cường",
    },
    {
      vaiTro: "theme",
      tenDa: themeStone,
      mauSac: STONE_COLORS[themeStone] || "#FFD700",
      yNghia: STONE_MEANINGS[themeStone] || "Chủ đề",
    },
  ]

  // Apply negative filters
  const { bangDa: filteredBangDa, applied: appliedFilters } = applyNegativeFilters(
    bangDa,
    input.mauKhongMuon
  )

  bangDa = filteredBangDa

  // Get charm suggestions
  const charmGoiY = getCharmSuggestions(input.suMenh)

  // Get layout suggestion
  const layoutDeXuat = getLayoutSuggestion(input.phongCach, input.vibe)

  // Get main colors
  const mauChuDao = getMainColors(healingStone, boostStone, input.vibe)

  // Generate affirmation
  let affirmationText = input.affirmation?.trim() || ""
  let isAutoGenerated = false

  if (!affirmationText) {
    const affirmations: Record<string, string> = {
      stress: "Tôi bình an, tôi mạnh mẽ, tôi xứng đáng được yên tĩnh.",
      lost: "Tôi tin vào quá trình. Mỗi bước đi đều mang ý nghĩa.",
      anxious: "Tôi an toàn, tôi được bảo vệ, tôi tin tưởng cuộc sống.",
      angry: "Tôi bình tĩnh, tôi kiểm soát cảm xúc, tôi hòa bình.",
      bored: "Tôi rực rỡ, tôi có năng lượng, tôi khám phá điều mới.",
      happy: "Tôi duy trì vui vẻ, tôi chia sẻ năng lượng tích cực.",
      default: "Tôi đi đúng hướng. Bình tĩnh và bền bỉ, điều tốt sẽ đến.",
    }

    for (const [key, value] of Object.entries(affirmations)) {
      if (key !== "default" && input.trangThaiTinhThan?.toLowerCase().includes(key)) {
        affirmationText = value
        isAutoGenerated = true
        break
      }
    }

    if (!affirmationText) {
      affirmationText = affirmations.default
      isAutoGenerated = true
    }
  }

  // Summary points
  const tomTatChanDung = [
    `Chọn ${healingStone} vì trạng thái tinh thần hiện tại cần: giảm stress, bình tĩnh, chữa lành.`,
    `Kết hợp ${boostStone} để vượt qua rào cản: tập trung hành động, xua đi năng lượng xấu.`,
    `Sử dụng ${themeStone} để hỗ trợ mục tiêu: ${input.suMenh || "sự bình an"}.`,
  ]

  // Reasons for selection
  const lyDoChon = [
    `Đá chính (${mainStone}): Kết nối với yếu tố tự nhiên ${input.yeuToThienNhien || "được chọn"}, tạo nền tảng năng lượng.`,
    `Đá chữa lành (${healingStone}): Cụ thể hỗ trợ trạng thái "${input.trangThaiTinhThan || "cân bằng"}", giúp xua đi năng lượng xấu.`,
    `Vibe "${input.vibe || "nhẹ nhàng"}" được thể hiện qua phối màu ${mauChuDao.join(" + ")}, phù hợp phong cách "${input.phongCach || "cân bằng"}".`,
  ]

  // Generate reading card
  const tenVong =
    input.suMenh?.toLowerCase().includes("wealth")
      ? "Vòng Tài Lộc"
      : input.suMenh?.toLowerCase().includes("love")
        ? "Vòng Tình Yêu"
        : input.suMenh?.toLowerCase().includes("wisdom")
          ? "Vòng Trí Tuệ"
          : "Vòng Năng Lượng Cá Nhân"

  return {
    project: {
      name: "SoulGem AI",
      concept: "Cá nhân hóa vòng tay đá năng lượng theo 10 câu hỏi",
      businessModel: "D2C",
    },
    input,
    result: {
      tomTatChanDung,
      vongTayDeXuat: {
        tenVong,
        vibe: input.vibe || "Nhẹ nhàng",
        phongCach: input.phongCach || "Cân bằng",
        coTayCm,
        nganSach,
        kichThuocHatMm,
        soHatDuKien,
        bangDa,
        charmGoiY,
        layoutDeXuat,
        mauChuDao,
        negativeFiltersApplied: appliedFilters,
        lyDoChon,
      },
      readingCard: {
        tieuDe: `Thẻ Năng Lượng của ${input.name || "Bạn"}`,
        thongDiepChinh: `Chiếc vòng này được thiết kế riêng cho bạn để hỗ trợ ${input.suMenh || "sự bình an"} trong cuộc sống. ${healingStone} sẽ giúp bạn giải phóng căng thẳng, trong khi ${boostStone} giúp bạn vượt qua ${input.raoCan || "các rào cản"}. Mang chiếc vòng này gần tim bạn, hãy nhớ rằng bạn không bao giờ đơn độc trên con đường này.`,
        giaiThichNgan: [
          `Bộ đá được chọn phản ánh năng lượng hiện tại của bạn, không phải để "sửa chữa" mà để "hỗ trợ" bạn bước vào giai đoạn tiếp theo.`,
          `Mỗi viên đá là một lời nhắc nhở hàng ngày: bạn mạnh mẽ, bạn xứng đáng, và bạn đang đi đúng hướng.`,
        ],
        affirmation: {
          text: affirmationText,
          autoGenerated: isAutoGenerated,
        },
      },
    },
  }
}
