// SoulGem AI - Bracelet Recommendation Engine
// Rule-based with AI enhancement for personalized energy reading

export interface BraceletRecommendationInput {
  ngaySinh?: string
  cungHoangDao?: string
  gioiTinh?: string
  yeuToThienNhien?: string
  trangThaiTinhThan?: string
  raoCan?: string
  suMenh?: string
  vibe?: string
  phongCach?: string
  mauKhongMuon?: string
  coTayCm?: number
  nganSach?: number
  affirmation?: string
}

export interface DaInfo {
  vaiTro: "main" | "healing" | "boost" | "theme"
  tenDa: string
  mauSac: string
  yNghia: string
}

export interface BraceletRecommendation {
  project: {
    name: string
    concept: string
    businessModel: string
  }
  input: BraceletRecommendationInput
  result: {
    tomTatChanDung: string[]
    vongTayDeXuat: {
      tenVong: string
      vibe: string
      phongCach: string
      coTayCm: number
      nganSach: number
      kichThuocHatMm: number
      soHatDuKien: string
      bangDa: DaInfo[]
      charmGoiY: Array<{ tenCharm: string; yNghia: string }>
      layoutDeXuat: string
      mauChuDao: string[]
      negativeFiltersApplied: string[]
      lyDoChon: string[]
    }
    readingCard: {
      tieuDe: string
      thongDiepChinh: string
      giaiThichNgan: string[]
      affirmation: {
        text: string
        autoGenerated: boolean
      }
    }
  }
}

// Danh sách đá được phép dùng
const ALLOWED_STONES = [
  "Thạch anh trắng",
  "Thạch anh tím",
  "Mắt hổ",
  "Thạch anh vàng",
  "Thạch anh hồng",
  "Đá mặt trăng",
  "Aquamarine",
  "Fluorite",
  "Thạch anh xanh",
  "Obsidian đen",
  "Đá mặt trời",
]

// Color mapping
const STONE_COLORS: Record<string, string> = {
  "Thạch anh trắng": "#F5F5F5",
  "Thạch anh tím": "#9966CC",
  "Mắt hổ": "#B8860B",
  "Thạch anh vàng": "#FFD700",
  "Thạch anh hồng": "#FFB6C1",
  "Đá mặt trăng": "#E8D5D5",
  Aquamarine: "#7FFFD4",
  Fluorite: "#B0C4DE",
  "Thạch anh xanh": "#1E90FF",
  "Obsidian đen": "#1C1C1C",
  "Đá mặt trời": "#FFA500",
}

// Stone meaning mapping
const STONE_MEANINGS: Record<string, string> = {
  "Thạch anh trắng":
    "Làm sạch năng lượng, bảo vệ, tạo sự rõ ràng trong suy nghĩ và ý định",
  "Thạch anh tím":
    "Giảm stress, bình tĩnh tâm trí, cân bằng cảm xúc, hỗ trợ thiền định",
  "Mắt hổ":
    "Tập trung, hành động, xua đi năng lượng xấu, tăng cường sự tự tin",
  "Thạch anh vàng": "Tạo năng lượng tích cực, hấp dẫn may mắn, tài lộc",
  "Thạch anh hồng": "Tình yêu, tự yêu thương, chữa lành tổn thương cảm xúc",
  "Đá mặt trăng": "An thần, cân bằng hormone nữ, kết nối trực giác",
  Aquamarine: "Hạ nhiệt, bình tĩnh, kết nối tiếp xúc hiệu quả",
  Fluorite: "Tập trung, rõ ràng suy nghĩ, hỗ trợ học tập",
  "Thạch anh xanh": "Hồi phục, cân bằng thể chất, chữa lành bệnh lành",
  "Obsidian đen": "Bảo vệ, xua đi năng lượng xấu, hỗ trợ nhận thức",
  "Đá mặt trời": "Tự tin, tỏa sáng, mang lại ấm áp và tích cực",
}

// Rule-based mapping functions
function getHealingStone(trangThaiTinhThan?: string): string {
  if (!trangThaiTinhThan) return "Thạch anh tím" // default fallback

  const mappings: Record<string, string> = {
    "stress": "Thạch anh tím",
    "lost": "Fluorite",
    "anxious": "Đá mặt trăng",
    "angry": "Aquamarine",
    "bored": "Thạch anh vàng",
    "happy": "Thạch anh hồng",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (trangThaiTinhThan.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch anh tím"
}

function getBoostStone(raoCan?: string): string {
  if (!raoCan) return "Mắt hổ" // default fallback

  const mappings: Record<string, string> = {
    "procrastination": "Mắt hổ",
    "confidence": "Đá mặt trời",
    "bad_luck": "Obsidian đen",
    "health": "Thạch anh xanh",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (raoCan.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Mắt hổ"
}

function getThemeStone(suMenh?: string): string {
  if (!suMenh) return "Thạch anh vàng" // default fallback

  const mappings: Record<string, string> = {
    "wealth": "Thạch anh vàng",
    "love": "Thạch anh hồng",
    "wisdom": "Fluorite",
    "health": "Thạch anh tím",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (suMenh.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch anh vàng"
}

function getMainStone(yeuToThienNhien?: string): string {
  if (!yeuToThienNhien) return "Thạch anh trắng"

  const mappings: Record<string, string> = {
    "fire": "Thạch anh vàng",
    "water": "Aquamarine",
    "earth": "Fluorite",
    "air": "Thạch anh trắng",
    "metal": "Obsidian đen",
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (yeuToThienNhien.toLowerCase().includes(key)) {
      return value
    }
  }

  return "Thạch anh trắng"
}

function getCharmSuggestions(
  suMenh?: string
): Array<{ tenCharm: string; yNghia: string }> {
  if (!suMenh) {
    return [
      { tenCharm: "Hoa Sen", yNghia: "Bình an, tinh khiết" },
      { tenCharm: "Chữ Lộc", yNghia: "Tài lộc, may mắn" },
    ]
  }

  const mappings: Record<
    string,
    Array<{ tenCharm: string; yNghia: string }>
  > = {
    wealth: [
      { tenCharm: "Tiền Tài", yNghia: "Hấp dẫn tài lộc, may mắn kinh doanh" },
      {
        tenCharm: "Sự Nghiệp",
        yNghia: "Thăng tiến, phát triển công việc",
      },
    ],
    love: [
      { tenCharm: "Trái Tim", yNghia: "Tình yêu, kết nối" },
      { tenCharm: "Đôi Cánh", yNghia: "Tự do, kết nối linh hồn" },
    ],
    wisdom: [
      { tenCharm: "Sách", yNghia: "Học tập, trí tuệ" },
      { tenCharm: "Mắt Thứ Ba", yNghia: "Trực giác, ý thức" },
    ],
    health: [
      { tenCharm: "Hoa Sen", yNghia: "Sạch sẽ, bình yên" },
      {
        tenCharm: "Cây Sống",
        yNghia: "Sức sống, phục hồi",
      },
    ],
  }

  for (const [key, value] of Object.entries(mappings)) {
    if (suMenh?.toLowerCase().includes(key)) {
      return value
    }
  }

  return [
    { tenCharm: "Bình Yên", yNghia: "Cân bằng năng lượng" },
  ]
}

function calculateBeadCount(coTayCm: number = 16): string {
  if (coTayCm <= 15) return "17-19"
  if (coTayCm <= 17) return "19-21"
  if (coTayCm <= 19) return "21-23"
  return "23-25"
}

function getBeadSize(nganSach: number = 99000): number {
  return nganSach >= 149000 ? 8 : 6
}

function getLayoutSuggestion(phongCach?: string, vibe?: string): string {
  if (phongCach?.toLowerCase().includes("minimal")) {
    return "1-2 loại đá chính, bố cục sạch sẽ, 1 charm nhỏ tinh tế"
  }
  if (phongCach?.toLowerCase().includes("nổi loạn")) {
    return "Tương phản mạnh, hạt nổi bật, layout phá cách và cá tính"
  }
  if (phongCach?.toLowerCase().includes("vintage")) {
    return "Tone đất ấm, đá mờ, charm cổ điển, bố cục truyền thống"
  }
  if (phongCach?.toLowerCase().includes("nữ tính")) {
    return "Tông hồng/tím, charm tim/hoa, layout mềm mại và nữ tính"
  }

  // Default based on vibe
  if (vibe?.toLowerCase().includes("mạnh")) {
    return "Tương phản rõ, điểm nhấn mạnh, layout cân đối nhưng nổi bật"
  }

  return "Bố cục cân đối, dễ phối đồ, màu sắc hài hòa, charm đa dụng"
}

function getMainColors(
  healingStone: string,
  boostStone: string,
  vibe?: string
): string[] {
  const stoneColorMap: Record<string, string> = STONE_COLORS

  const primary = stoneColorMap[healingStone] || "#9966CC"
  const secondary = stoneColorMap[boostStone] || "#B8860B"

  if (vibe?.toLowerCase().includes("nhẹ")) {
    return [primary, secondary]
  }

  return [secondary, primary]
}

function applyNegativeFilters(
  bangDa: DaInfo[],
  mauKhongMuon?: string
): { bangDa: DaInfo[]; applied: string[] } {
  const applied: string[] = []

  if (!mauKhongMuon || mauKhongMuon.toLowerCase().includes("không")) {
    return { bangDa, applied }
  }

  // Remove Obsidian đen if dark tone not wanted
  if (
    mauKhongMuon.toLowerCase().includes("tối") ||
    mauKhongMuon.toLowerCase().includes("đen")
  ) {
    bangDa = bangDa.filter((d) => d.tenDa !== "Obsidian đen")
    if (!bangDa.find((d) => d.vaiTro === "boost")) {
      bangDa.push({
        vaiTro: "boost",
        tenDa: "Thạch anh trắng",
        mauSac: STONE_COLORS["Thạch anh trắng"],
        yNghia: STONE_MEANINGS["Thạch anh trắng"],
      })
    }
    applied.push("Loại bỏ Obsidian đen (tông tối)")
  }

  // Limit colors if too many wanted
  if (
    mauKhongMuon.toLowerCase().includes("nhiều") ||
    mauKhongMuon.toLowerCase().includes("sặc")
  ) {
    if (bangDa.length > 3) {
      bangDa = bangDa.slice(0, 2)
      bangDa.push({
        vaiTro: "theme",
        tenDa: "Thạch anh trắng",
        mauSac: STONE_COLORS["Thạch anh trắng"],
        yNghia: STONE_MEANINGS["Thạch anh trắng"],
      })
    }
    applied.push("Giới hạn số loại đá (tối giản màu sắc)")
  }

  return { bangDa, applied }
}

export function getBraceletRecommendation(
  input: BraceletRecommendationInput
): BraceletRecommendation {
  // Apply fallbacks for missing data
  const coTayCm = input.coTayCm || 16
  const nganSach = input.nganSach || 99000
  const kichThuocHatMm = getBeadSize(nganSach)
  const soHatDuKien = calculateBeadCount(coTayCm)

  // Get stone recommendations
  const mainStone = getMainStone(input.yeuToThienNhien)
  const healingStone = getHealingStone(input.trangThaiTinhThan)
  const boostStone = getBoostStone(input.raoCan)
  const themeStone = getThemeStone(input.suMenh)

  // Build bộ đá
  let bangDa: DaInfo[] = [
    {
      vaiTro: "main",
      tenDa: mainStone,
      mauSac: STONE_COLORS[mainStone] || "#F5F5F5",
      yNghia: STONE_MEANINGS[mainStone] || "Năng lượng chính",
    },
    {
      vaiTro: "healing",
      tenDa: healingStone,
      mauSac: STONE_COLORS[healingStone] || "#9966CC",
      yNghia: STONE_MEANINGS[healingStone] || "Chữa lành",
    },
    {
      vaiTro: "boost",
      tenDa: boostStone,
      mauSac: STONE_COLORS[boostStone] || "#B8860B",
      yNghia: STONE_MEANINGS[boostStone] || "Tăng cường",
    },
    {
      vaiTro: "theme",
      tenDa: themeStone,
      mauSac: STONE_COLORS[themeStone] || "#FFD700",
      yNghia: STONE_MEANINGS[themeStone] || "Chủ đề",
    },
  ]

  // Apply negative filters
  const { bangDa: filteredBangDa, applied: appliedFilters } = applyNegativeFilters(
    bangDa,
    input.mauKhongMuon
  )

  bangDa = filteredBangDa

  // Get charm suggestions
  const charmGoiY = getCharmSuggestions(input.suMenh)

  // Get layout suggestion
  const layoutDeXuat = getLayoutSuggestion(input.phongCach, input.vibe)

  // Get main colors
  const mauChuDao = getMainColors(healingStone, boostStone, input.vibe)

  // Generate affirmation
  let affirmationText = input.affirmation?.trim() || ""
  let isAutoGenerated = false

  if (!affirmationText) {
    const affirmations: Record<string, string> = {
      stress: "Tôi bình an, tôi mạnh mẽ, tôi xứng đáng được yên tĩnh.",
      lost: "Tôi tin vào quá trình. Mỗi bước đi đều mang ý nghĩa.",
      anxious: "Tôi an toàn, tôi được bảo vệ, tôi tin tưởng cuộc sống.",
      angry: "Tôi bình tĩnh, tôi kiểm soát cảm xúc, tôi hòa bình.",
      bored: "Tôi rực rỡ, tôi có năng lượng, tôi khám phá điều mới.",
      happy: "Tôi duy trì vui vẻ, tôi chia sẻ năng lượng tích cực.",
      default: "Tôi đi đúng hướng. Bình tĩnh và bền bỉ, điều tốt sẽ đến.",
    }

    for (const [key, value] of Object.entries(affirmations)) {
      if (key !== "default" && input.trangThaiTinhThan?.toLowerCase().includes(key)) {
        affirmationText = value
        isAutoGenerated = true
        break
      }
    }

    if (!affirmationText) {
      affirmationText = affirmations.default
      isAutoGenerated = true
    }
  }

  // Summary points
  const tomTatChanDung = [
    `Chọn ${healingStone} vì trạng thái tinh thần hiện tại cần: giảm stress, bình tĩnh, chữa lành.`,
    `Kết hợp ${boostStone} để vượt qua rào cản: tập trung hành động, xua đi năng lượng xấu.`,
    `Sử dụng ${themeStone} để hỗ trợ mục tiêu: ${input.suMenh || "sự bình an"}.`,
  ]

  // Reasons for selection
  const lyDoChon = [
    `Đá chính (${mainStone}): Kết nối với yếu tố tự nhiên ${input.yeuToThienNhien || "được chọn"}, tạo nền tảng năng lượng.`,
    `Đá chữa lành (${healingStone}): Cụ thể hỗ trợ trạng thái "${input.trangThaiTinhThan || "cân bằng"}", giúp xua đi năng lượng xấu.`,
    `Vibe "${input.vibe || "nhẹ nhàng"}" được thể hiện qua phối màu ${mauChuDao.join(" + ")}, phù hợp phong cách "${input.phongCach || "cân bằng"}".`,
  ]

  // Generate reading card
  const tenVong =
    input.suMenh?.toLowerCase().includes("wealth")
      ? "Vòng Tài Lộc"
      : input.suMenh?.toLowerCase().includes("love")
        ? "Vòng Tình Yêu"
        : input.suMenh?.toLowerCase().includes("wisdom")
          ? "Vòng Trí Tuệ"
          : "Vòng Năng Lượng Cá Nhân"

  return {
    project: {
      name: "SoulGem AI",
      concept: "Cá nhân hóa vòng tay đá năng lượng theo 10 câu hỏi",
      businessModel: "D2C",
    },
    input,
    result: {
      tomTatChanDung,
      vongTayDeXuat: {
        tenVong,
        vibe: input.vibe || "Nhẹ nhàng",
        phongCach: input.phongCach || "Cân bằng",
        coTayCm,
        nganSach,
        kichThuocHatMm,
        soHatDuKien,
        bangDa,
        charmGoiY,
        layoutDeXuat,
        mauChuDao,
        negativeFiltersApplied: appliedFilters,
        lyDoChon,
      },
      readingCard: {
        tieuDe: `Thẻ Năng Lượng của ${input.name || "Bạn"}`,
        thongDiepChinh: `Chiếc vòng này được thiết kế riêng cho bạn để hỗ trợ ${input.suMenh || "sự bình an"} trong cuộc sống. ${healingStone} sẽ giúp bạn giải phóng căng thẳng, trong khi ${boostStone} giúp bạn vượt qua ${input.raoCan || "các rào cản"}. Mang chiếc vòng này gần tim bạn, hãy nhớ rằng bạn không bao giờ đơn độc trên con đường này.`,
        giaiThichNgan: [
          `Bộ đá được chọn phản ánh năng lượng hiện tại của bạn, không phải để "sửa chữa" mà để "hỗ trợ" bạn bước vào giai đoạn tiếp theo.`,
          `Mỗi viên đá là một lời nhắc nhở hàng ngày: bạn mạnh mẽ, bạn xứng đáng, và bạn đang đi đúng hướng.`,
        ],
        affirmation: {
          text: affirmationText,
          autoGenerated: isAutoGenerated,
        },
      },
    },
  }
}
