// Dữ liệu đá quý - MẢNH Collection

export const STONES = {
  citrine: {
    id: "citrine",
    name: "Citrine",
    vietnameseName: "Thạch Anh Vàng",
    color: "#FDB462",
    meaning: "Tài lộc & sự phát triển",
    energy: "Năng lượng Thịnh Vượng",
    description: "Đá vàng tươi sáng, mang lại sự lạc quan và tự tin",
  },
  clearQuartz: {
    id: "clear-quartz",
    name: "Clear Quartz",
    vietnameseName: "Thạch Anh Trắng",
    color: "#FFFFFF",
    meaning: "Sáng suốt & làm sạch năng lượng",
    energy: "Năng lượng Tĩnh Lặng",
    description: "Đá trong suốt, giúp thanh lọc tâm trí và năng lượng",
  },
  amethyst: {
    id: "amethyst",
    name: "Amethyst",
    vietnameseName: "Thạch Anh Tím",
    color: "#9966CC",
    meaning: "Bình an & tâm linh",
    energy: "Năng lượng Tĩnh Lặng",
    description: "Đá tím nhạt, mang lại sự yên bình và cân bằng",
  },
  fluorite: {
    id: "fluorite",
    name: "Fluorite",
    vietnameseName: "Huỳnh Thạch",
    color: "#7744CC",
    meaning: "Tập trung & rõ ràng",
    energy: "Năng lượng Tích cực",
    description: "Đá với các sắc tính khác nhau, giúp tập trung tinh thần",
  },
  moonstone: {
    id: "moonstone",
    name: "Moonstone",
    vietnameseName: "Đá Mặt Trăng",
    color: "#E8E8FF",
    meaning: "Cảm xúc & nữ tính",
    energy: "Năng lượng Chữa Lành",
    description: "Đá với ánh sáng mặt trăng, giúp cân bằng cảm xúc",
  },
  sunstone: {
    id: "sunstone",
    name: "Sunstone",
    vietnameseName: "Đá Mặt Trời",
    color: "#FF8800",
    meaning: "Sinh lực & tràn đầy năng lượng",
    energy: "Năng lượng Tích cực",
    description: "Đá cam rực rỡ, mang lại sự sôi nổi và nhiệt huyết",
  },
  labradorite: {
    id: "labradorite",
    name: "Labradorite",
    vietnameseName: "Đá Hắc Nguyệt Quang",
    color: "#8B7355",
    meaning: "Bảo vệ & chuyển hóa",
    energy: "Năng lượng Tĩnh Lặng",
    description: "Đá nâu xám với ánh sáng kỳ lạ, bảo vệ năng lượng",
  },
  peridot: {
    id: "peridot",
    name: "Peridot",
    vietnameseName: "Olit",
    color: "#CCFF00",
    meaning: "Phát triển & chữa lành",
    energy: "Năng lượng Thịnh Vượng",
    description: "Đá xanh lá mạ sáng, mang lại sự tươi mới và tái sinh",
  },
  aquamarine: {
    id: "aquamarine",
    name: "Aquamarine",
    vietnameseName: "Bê Tông Thạch",
    color: "#00BFFF",
    meaning: "Bình yên & giao tiếp",
    energy: "Năng lượng Tĩnh Lặng",
    description: "Đá xanh biển, giúp thanh tịnh và trao đổi tốt",
  },
  roseQuartz: {
    id: "rose-quartz",
    name: "Rose Quartz",
    vietnameseName: "Thạch Anh Hồng",
    color: "#FF69B4",
    meaning: "Yêu thương & tự trọng",
    energy: "Năng lượng Chữa Lành",
    description: "Đá hồng nhạt, biểu tượng của tình yêu và lòng trắc ẩn",
  },
  garnet: {
    id: "garnet",
    name: "Garnet",
    vietnameseName: "Ngọc Hồng Lựu",
    color: "#DC143C",
    meaning: "Sức sống & đam mê",
    energy: "Năng lượng Tích cực",
    description: "Đá đỏ sẫm, mang lại năng lượng và sức mạnh",
  },
}

export const ALL_STONES = [
  STONES.citrine,
  STONES.clearQuartz,
  STONES.amethyst,
  STONES.fluorite,
  STONES.moonstone,
  STONES.sunstone,
  STONES.labradorite,
  STONES.peridot,
  STONES.aquamarine,
  STONES.roseQuartz,
  STONES.garnet,
]
